ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Controllers/GameController.cs
using ConestogaVirtualGameStore.Framework.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ConestogaVirtualGameStore.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly GameStoreContext db = new GameStoreContext();
        // GET: Game
        public ActionResult Index()
        {
            var accountId = Convert.ToInt32(Session["accountId"]);
            if(accountId != 0)
            {
                var person = db.Account.SingleOrDefault(x => x.AccountId == accountId);
                var employee = db.Employee.SingleOrDefault(x => x.PersonId == person.PersonId);
                // if the account id is for employee, make the employee logout and show the login screen
                if (employee != null)
                {
                    //ModelState.AddModelError("UserName", "Entered UserName is for Customer. Try it on Customer's site");
                    TempData["message"] = "You cannot access the Customer site with the Employee user name";
                    FormsAuthentication.SignOut();
                    Session.Clear();
                    return RedirectToAction("Login", "Account");
                }
            }

            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            
            if (TempData["logout"] != null && TempData["logout"].ToString() == "logout")
            {//when logout, just show the game list
                return View(db.Game.ToList());
            }
            else if(TempData["logout"] == null && latestCart == null)
            {//it's not logout, but need to show the count of line item on the Cart when customer never added item to the Cart
                TempData["lineItemCount"] = 0;
                return View(db.Game.ToList());
            }
            else if (accountId == 0)
            {//session expired
                TempData["message"] = "Session expired. Login please";
                return RedirectToAction("Login", "Account");
            }
            else
            {//show the count of line item on the Cart
                if (latestCart != null)
                {
                    var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                    //if the first line item's Order id is null, all list item for the cart id has all null for order id
                    //and it means the cart isn't proceeded yet
                    //so in order to show the count of line item list beside the Cart
                    if (lineItemList[0].OrderId == null)
                    {
                        TempData["lineItemCount"] = lineItemList.Count;
                    }
                    else
                    {
                        TempData["lineItemCount"] = 0;
                    }
                }

                return View(db.Game.ToList());
            }
        }

        // GET: Review/Create
        public ActionResult CreateReview(string gameName, int gameId)
        {
            TempData["gameName"] = gameName;
            TempData["gameId"] = gameId;

            CountLineItemInCart();
            //ViewBag.GameId = new SelectList(db.Game, "GameId", "Name");
            return View();
        }

        // POST: Review/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateReview([Bind(Include = "ReviewId,Ratings,Details,GameId")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Review.Add(review);
                db.SaveChanges();
                //return Redirect("/Game/Details/" + review.GameId);
                CountLineItemInCart();
                TempData["reviewMessage"] = "Thank you for your feedback! Your review will be added once approved by administrator.";
                return RedirectToAction("Details", new { id = review.GameId });
            }

            ViewBag.GameId = new SelectList(db.Game, "GameId", "Name", review.GameId);
            return View(review);
        }

        // GET: Game/Details/5
        public ActionResult Details(int? id)
        {
            TempData["averageRating"] = null;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            double averageRating = CalculateAverageRating(id);
            TempData["averageRating"] = averageRating;
            if (game == null)
            {
                return HttpNotFound();
            }
            TempData["gameName"] = game.Name;

            ////1. get latest cart for the current account
            //var accountId = Convert.ToInt32(Session["accountId"]);
            CountLineItemInCart(game.GameId);
            IEnumerable<Review> reviews = new List<Review>();
            reviews = db.Review.Where(x => x.GameId == id && x.Approved).ToList();

            ViewData["reviews"] = reviews;
            return View(game);
        }

        private void CountLineItemInCart(int gameId)
        {
            //1. get latest cart for the current account
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            if (latestCart != null)
            {
                var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                //2. if the first line item's Order id is null, all list item for the cart id has all null for order id
                //and it means the cart isn't proceeded yet
                //so in order to show the count of line item list beside the Cart
                if (lineItemList[0].OrderId == null)
                {
                    TempData["lineItemCount"] = lineItemList.Count;
                    foreach (var lineItem in lineItemList)
                    {
                        if (lineItem.GameId == gameId)
                        {
                            TempData["selectedQuantity"] = lineItem.Quantity;
                            break;
                        }
                    }
                }
                else
                {
                    TempData["lineItemCount"] = 0;
                }
            }
            else
            {
                TempData["lineItemCount"] = 0;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchGame(string keyword)
        {
            if (ModelState.IsValid)
            {
                var gameResultList = db.Game.Where(x => x.Name.Contains(keyword)).ToList();
                ViewBag.keyword = keyword;
                //db.SaveChanges();

                CountLineItemInCart();              
                return View("GameResultList", gameResultList);
            }
            return View();
        }

        private void CountLineItemInCart()
        {
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            if (latestCart != null)
            {
                var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                //if the first line item's Order id is null, all list item for the cart id has all null for order id
                //and it means the cart isn't proceeded yet
                //so in order to show the count of line item list beside the Cart
                if (lineItemList[0].OrderId == null)
                {
                    TempData["lineItemCount"] = lineItemList.Count;
                }
                else
                {
                    TempData["lineItemCount"] = 0;
                }
            }
        }
        public ActionResult SearchGameWithKeyword(string keyword)
        {
            //string keyword = ViewBag.keyword;
            var gameResultList = db.Game.Where(x => x.Name.Contains(keyword)).ToList();

            ViewBag.keyword = keyword;
            CountLineItemInCart();
            //db.SaveChanges();
            //return Redirect("/Game/Details/" + review.GameId);
            return View("GameResultList", gameResultList);
        }

        public double CalculateAverageRating(int? gameId)
        {
            if(db.Review.Where(a => a.GameId == gameId && a.Approved == true).Count() == 0)
            {
                return 0;
            }
            int star5 = db.Review.Where(a => a.GameId == gameId && a.Ratings == 5 && a.Approved == true).Count();
            int star4 = db.Review.Where(a => a.GameId == gameId && a.Ratings == 4 && a.Approved == true).Count();
            int star3 = db.Review.Where(a => a.GameId == gameId && a.Ratings == 3 && a.Approved == true).Count();
            int star2 = db.Review.Where(a => a.GameId == gameId && a.Ratings == 2 && a.Approved == true).Count();
            int star1 = db.Review.Where(a => a.GameId == gameId && a.Ratings == 1 && a.Approved == true).Count();

            double averageRating = 0;

            averageRating = (double)(5 * star5 + 4 * star4 + 3 * star3 + 2 * star2 + 1 * star1) / (star1 + star2 + star3 + star4 + star5);

            averageRating = Math.Round(averageRating, 1);

            return averageRating;
        }
    }
}

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using ConestogaVirtualGameStore.Framework.Entities;
using ConestogaVirtualGameStore.Web.Models;

namespace ConestogaVirtualGameStore.Web.Controllers
{
    [Authorize(Roles = "Customer")]
    public class PersonController : Controller
    {
        private readonly GameStoreContext db = new GameStoreContext();

        // GET: Person
        public ActionResult Index()
        {
            CountLineItemInCart();
            return View(db.Person.ToList());
        }

        // GET: Person/Details/5
        public ActionResult Details(int? id)
        {
            id = Convert.ToInt32(Session["accountId"]);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Person.Find(id);
            Account account = db.Account.FirstOrDefault(a => a.PersonId == id);
            Address billingAddress = db.Address.FirstOrDefault(a => a.PersonId == id && a.AddressType == AddressType.Billing);
            Address shippingAddress = db.Address.FirstOrDefault(a => a.PersonId == id && a.AddressType == AddressType.Shipping);

            ProfileViewModel profile = new ProfileViewModel
            {
                Person = person,
                Account = account,
                BillingAddress = billingAddress,
                ShippingAddress = shippingAddress,
                UseSameAddress = false
            };
            if (billingAddress.Street == shippingAddress.Street)
            {
                profile.UseSameAddress = true;
            }
            if (person == null)
            {
                return HttpNotFound();
            }

            CountLineItemInCart();

            return View(profile);
        }

        private void CountLineItemInCart()
        {
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            if (latestCart != null)
            {
                var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                //if the first line item's Order id is null, all list item for the cart id has all null for order id
                //and it means the cart isn't proceeded yet
                //so in order to show the count of line item list beside the Cart
                if (lineItemList[0].OrderId == null)
                {
                    TempData["lineItemCount"] = lineItemList.Count;
                }
                else
                {
                    TempData["lineItemCount"] = 0;
                }
            }
        }

        // GET: Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonId,FirstName,LastName,DateOfBirth,PhoneNumber,Email,Gender")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Person.Add(person);
                db.SaveChanges();
                CountLineItemInCart();
                return RedirectToAction("Index");
            }

            CountLineItemInCart();
            return View(person);
        }

        // GET: Person/Edit/5
        public ActionResult Edit(int? id)
        {
            id = Convert.ToInt32(Session["accountId"]);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Person.Find(id);
            Account account = db.Account.FirstOrDefault(a => a.PersonId == id);
            Address billingAddress = db.Address.FirstOrDefault(a => a.PersonId == id && a.AddressType == AddressType.Billing);
            Address shippingAddress = db.Address.FirstOrDefault(a => a.PersonId == id && a.AddressType == AddressType.Shipping);

            ProfileViewModel profile = new ProfileViewModel
            {
                Person = person,
                Account = account,
                BillingAddress = billingAddress,
                ShippingAddress = shippingAddress,
                UseSameAddress = false
            };
            if (person == null)
            {
                return HttpNotFound();
            }

            CountLineItemInCart();

            return View(profile);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProfileViewModel profile)
        {
            if(ModelState.IsValid)
            {
                if (profile.Person.PhoneNumber != null)
                {
                    Regex phoneRegex = new Regex(@"^\(?\d{3}\)?-? *\d{3}-? *-?\d{4}$");
                    if (!phoneRegex.IsMatch(profile.Person.PhoneNumber))
                    {
                        ModelState.AddModelError("Person.PhoneNumber", "Invalid Phone Number");
                        CountLineItemInCart();
                        return View(profile);
                    }
                }

                if (profile.BillingAddress.PostalCode != null)
                {
                    Regex postalCodeRegex = new Regex(@"^[A-z][0-9][A-z] ?[0-9][A-z][0-9]$");
                    if(!postalCodeRegex.IsMatch(profile.BillingAddress.PostalCode))
                    {
                        ModelState.AddModelError("BillingAddress.PostalCode", "Invalid Postal Code");
                        CountLineItemInCart();

                        return View(profile);
                    }

                }

                if (profile.UseSameAddress)
                {
                    profile.CopyAddresses();
                }

                db.Entry(profile.Person).State = EntityState.Modified;
                //db.Entry(profile.Account).State = EntityState.Modified;
                db.Entry(profile.BillingAddress).State = EntityState.Modified;
                db.Entry(profile.ShippingAddress).State = EntityState.Modified;
                db.SaveChanges();

                CountLineItemInCart();
                return RedirectToAction("Index","Profile");
            }

            CountLineItemInCart();
            return View(profile);
        }

        // GET: Person/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Person.Find(id);
            db.Person.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Views/Person/Delete.cshtml
@model ConestogaVirtualGameStore.Framework.Entities.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Views/Person/Details.cshtml
@model ConestogaVirtualGameStore.Web.Models.ProfileViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details of @Session["userName"]</h2>

<div>
    @*<h4>Profile</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress.Province)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress.Province)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress.PostalCode)
        </dd>
    </dl>
</div>
@*<p style="font-weight:bold;">
*@<p >
    @Html.ActionLink("Edit", "Edit", new { id = Model.Person.PersonId }) |
    @Html.ActionLink("Return", "Index", "Game")
</p>

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Views/Person/Edit.cshtml
@model ConestogaVirtualGameStore.Web.Models.ProfileViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit","Person",FormMethod.Post))
{
    <h2>Edit Profile</h2>


    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Person</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Person.PersonId)
        @*@Html.HiddenFor(model => model.Account.AccountId)
        @Html.HiddenFor(model => model.Account.PersonId)*@
        @*@Html.HiddenFor(model => model.Account.AccountState)
        @Html.HiddenFor(model => model.Account.Attempts)
        @Html.HiddenFor(model => model.Account.CreatedOn)
        @Html.HiddenFor(model => model.Account.Password)
        @Html.HiddenFor(model => model.Account.Person)
        @Html.HiddenFor(model => model.Account.Preferences)
        @Html.HiddenFor(model => model.Account.UserName)*@
        @Html.HiddenFor(model => model.BillingAddress.AddressId)
        @Html.HiddenFor(model => model.BillingAddress.PersonId)
        @Html.HiddenFor(model => model.BillingAddress.AddressType)


        <div class="form-group">
            @Html.LabelFor(model => model.Person.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.DateOfBirth, new { htmlAttributes = new { @class = "form-control datepicker", @placeholder= "mm/dd/yy" } })
                @Html.ValidationMessageFor(model => model.Person.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <h3>Billing Address</h3>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress.Province, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress.Province, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress.Province, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UseSameAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UseSameAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UseSameAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        @*@if(model => model.UseSameAddress)*@
        @Html.Partial("_ShippingAddress")

        @*<div class="form-group">
            @Html.LabelFor(model => model.Account.ReceivePromotionalEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account.ReceivePromotionalEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account.ReceivePromotionalEmail, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div style="font-weight:bold;">
    @Html.ActionLink("Return", "Details", "Person")
</div>
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/jquery-ui.js"></script>
        <script src="~/Scripts/custom.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $(".datepicker").datepicker({
                    dateFormat: "mm/dd/yy",
                    changeMonth: true,
                    changeYear: true,
                    maxDate: "+0M +0D"
                });

            if ($('input[name$="UseSameAddress"]').prop("checked") == true) {
                $('#shipAddressForm').hide();
            }
                else if ($('input[name$="UseSameAddress"]').prop("checked") == false)) {
                $('#shipAddressForm').show();
            }
            
            $('#UseSameAddress').click(function () {
                if ($(this).prop("checked") == true) {
                    $('#shipAddressForm').hide();
                }
                else if ($(this).prop("checked") == false) {
                    $('#shipAddressForm').show();
                }
                //$('#shipAddressForm').toggle((this).prop("checked"));
            });
            });
        </script>
    }