ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Controllers/EventController.cs
using ConestogaVirtualGameStore.Framework.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.UI.WebControls;

namespace ConestogaVirtualGameStore.Web.Areas.Management.Controllers
{
    [Authorize(Roles = "Employee")]
    public class EventController : Controller
    {
        private GameStoreContext db = new GameStoreContext();

        // GET: Management/Event
        public ActionResult Index()
        {
            return View(db.Event.ToList());
            //return View();
        }

        // GET: Management/Event/Create
        public ActionResult Create()
        {
            //ViewBag.GameCategoryId = new SelectList(db.GameCategory, "GameCategoryId", "CategoryName");
            //ViewBag.GamePlatformCode = new SelectList(db.GamePlatform, "GamePlatformCode", "Name");
            return View();
        }

        // GET: Management/Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventSelected = db.Event.Find(id);
            if (eventSelected == null)
            {
                return HttpNotFound();
            }
            TempData["eventName"] = eventSelected.Title;

            return View(eventSelected);
        }

        // GET: Management/Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventSelected = db.Event.Find(id);
            if (eventSelected == null)
            {
                return HttpNotFound();
            }
            //ViewBag.GameCategoryId = new SelectList(db.GameCategory, "GameCategoryId", "CategoryName");
            //ViewBag.GamePlatformCode = new SelectList(db.GamePlatform, "GamePlatformCode", "Name");
            TempData["eventName"] = eventSelected.Title;
            return View(eventSelected);
        }
        // GET: Management/Game/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventSelected = db.Event.Find(id);
            if (eventSelected == null)
            {
                return HttpNotFound();
            }
            TempData["eventName"] = eventSelected.Title;
            return View(eventSelected);
        }


        // POST: Management/Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event eventEntered)
        {
            if (ModelState.IsValid)
            {
                db.Event.Add(eventEntered);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eventEntered);
        }

        // POST: Management/Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event eventModified)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventModified).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventModified);
        }

        // POST: Management/Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event eventSelected = db.Event.Find(id);
            db.Event.Remove(eventSelected);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        ConestogaVirtualGameStore.Web.Areas.Management.Reports.Report ds =
            new ConestogaVirtualGameStore.Web.Areas.Management.Reports.Report();
        public ActionResult EventReport()
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(1000);
            reportViewer.Height = Unit.Percentage(1000);

            var connectionString = ConfigurationManager.
                ConnectionStrings["GameStoreContext"].ConnectionString;

            SqlConnection conx = new SqlConnection(connectionString);
            SqlDataAdapter adp = new SqlDataAdapter("SELECT * FROM Event", conx);

            adp.Fill(ds, ds.Event.TableName);

            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Areas\Management\Reports\EventReport.rdlc";
            reportViewer.LocalReport.DataSources.Add(new ReportDataSource("EventDataSet", ds.Tables[0]));


            ViewBag.ReportViewer = reportViewer;

            return View();
        }
    }
}

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Controllers/EventController.cs
using ConestogaVirtualGameStore.Framework.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ConestogaVirtualGameStore.Web.Controllers
{
    public class EventController : Controller
    {
        private GameStoreContext db = new GameStoreContext();
        // GET: Event
        public ActionResult Index()
        {
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();

            if (TempData["logout"] != null && TempData["logout"].ToString() == "logout")
            {
                return View(db.Event.ToList());
            }

            else if (TempData["logout"] == null && latestCart == null)
            {
                TempData["lineItemCount"] = 0;
                return View(db.Event.ToList());
            }
            else if (accountId == 0)
            {
                TempData["message"] = "Session expired. Login please";
                return RedirectToAction("Login", "Account");
            }
            else
            {
                if (latestCart != null)
                {
                    CountLineItemInCart();
                }

                return View(db.Event.ToList());
            }           

        }

        private void CountLineItemInCart()
        {
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            if (latestCart != null)
            {
                var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                //if the first line item's Order id is null, all list item for the cart id has all null for order id
                //and it means the cart isn't proceeded yet
                //so in order to show the count of line item list beside the Cart
                if (lineItemList[0].OrderId == null)
                {
                    TempData["lineItemCount"] = lineItemList.Count;
                }
                else
                {
                    TempData["lineItemCount"] = 0;
                }
            }
        }

        // GET: Event/Details/5
        public ActionResult Details(int? id)
        {
            Session["eventId"] = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event eventSelected = db.Event.Find(id);
            if (eventSelected == null)
            {
                return HttpNotFound();
            }
            TempData["eventName"] = eventSelected.Title;


            //1. get latest cart for the current account
            var accountId = Convert.ToInt32(Session["accountId"]);
            var latestCart = db.Cart.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CreatedOn).FirstOrDefault();
            if (latestCart != null)
            {
                var lineItemList = db.LineItem.Where(x => x.CartId == latestCart.CartId).ToList();

                //2. if the first line item's Order id is null, all list item for the cart id has all null for order id
                //and it means the cart isn't proceeded yet
                //so in order to show the count of line item list beside the Cart
                if (lineItemList[0].OrderId == null)
                {
                    TempData["lineItemCount"] = lineItemList.Count;
                }
                else
                {
                    TempData["lineItemCount"] = 0;
                }
            }
            else
            {
                TempData["lineItemCount"] = 0;
            }

            return View("Details", eventSelected);
        }
    }
}

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/Create.cshtml
@model ConestogaVirtualGameStore.Framework.Entities.Event

@{
    ViewBag.Title = "Register New Event";
}

<h2>Register New Event</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "mm/dd/yy" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/jquery-ui.js"></script>
        <script src="~/Scripts/custom.js"></script>
        <script>
            $(function () {
                $(".datepicker").datepicker({
                    dateFormat: "mm/dd/yy",
                    changeMonth: true,
                    changeYear: true
                });
            });
        </script>
    }

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/Delete.cshtml
@model ConestogaVirtualGameStore.Framework.Entities.Event

@{
    ViewBag.Title = "Delete Event";
}

<h2>Delete Event @TempData["eventName"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/Details.cshtml
@model ConestogaVirtualGameStore.Framework.Entities.Event

@{
    ViewBag.Title = "Event Details";
}

<h2>Event Details of @TempData["eventName"]</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/Edit.cshtml
@model ConestogaVirtualGameStore.Framework.Entities.Event

@{
    ViewBag.Title = "Edit Event";
}

<h2>Edit Event @TempData["eventName"] </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "mm/dd/yy" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "mm/dd/yy" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/custom.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "mm/dd/yy",
                changeMonth: true,
                changeYear: true
            });
        });
    </script>
}

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/EventReport.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "Event List Report";
}
<br />
<br />
<h2>Event List Report</h2>
@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)

ConestogaVirtualGameStore.Web/ConestogaVirtualGameStore.Web/Areas/Management/Views/Event/Index.cshtml
@model IEnumerable<ConestogaVirtualGameStore.Framework.Entities.Event>

@{
    ViewBag.Title = "Event List";
}

<h2>Event List</h2>

<p>
    @Html.ActionLink("Create New Event", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("Details", "Event", new { Id=item.EventId})">@Html.DisplayFor(modelItem => item.Title)</a>
            </td>
            <td>
                <a href="@Url.Action("Details", "Event", new { Id=item.EventId})">@Html.DisplayFor(modelItem => item.Description)</a>
            </td>
            <td>
                <a href="@Url.Action("Details", "Event", new { Id=item.EventId})">@Html.DisplayFor(modelItem => item.StartDate)</a>
            </td>
            <td>
                <a href="@Url.Action("Details", "Event", new { Id=item.EventId})">@Html.DisplayFor(modelItem => item.EndDate)</a>
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EventId }) |
                @Html.ActionLink("Details", "Details", new { id = item.EventId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EventId })
            </td>
        </tr>
    }

</table>